ip              = '127.0.0.1'
port            = 8000
db              = './tlm.db'
mainsite        = 'http://localhost:8000'
appname         = 'outpost'
createdirs      = false
altmainsite     = []
file_tmp_path   = './temp'
file_path       = './files'
